export const FETCH_POSTS = 'POST/FETCH_POSTS'
export const CHANGE_LOAD_VALUE = 'POST/CHANGE_LOAD_VALUE'
export const REQUEST_POSTS = 'POST/REQUEST_POSTS'

export const SHOW_LOADER = 'APP/SHOW_LOADER'
export const HIDE_LOADER = 'APP/HIDE_LOADER'
export const CHANGE_SIDER_VISIBILITY = 'APP/CHANGE_SIDER_VISIBILITY'
export const CHANGE_THEME = 'APP/CHANGE_THEME'

export const RESET = 'APP/RESET'

export const FETCH_USER = 'USER/FETCH_USER'
export const REQUEST_USER = 'USER/REQUEST_USER'
