export const FETCH_POSTS = 'POST/FETCH_POSTS'
export const CHANGE_LOAD_VALUE = 'POST/CHANGE_LOAD_VALUE'
export const REQUEST_POSTS = 'POST/REQUEST_POSTS'

export const SHOW_LOADER = 'APP/SHOW_LOADER'
export const HIDE_LOADER = 'APP/HIDE_LOADER'
export const SHOW_ALERT = 'APP/SHOW_ALERT'
export const HIDE_ALERT = 'APP/HIDE_ALERT'
export const CHANGE_SIDER_VISIBILITY = 'APP/CHANGE_SIDER_VISIBILITY'
